USE carpooling;

ALTER TABLE Usuarios
    ADD COLUMN IF NOT EXISTS FotoPerfil MEDIUMTEXT NULL AFTER `Contraseña`,
    ADD COLUMN IF NOT EXISTS Descripcion TEXT NULL AFTER FotoPerfil,
    ADD COLUMN IF NOT EXISTS Preferencias TEXT NULL AFTER Descripcion,
    ADD COLUMN IF NOT EXISTS Saldo DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER Preferencias,
    ADD COLUMN IF NOT EXISTS TokenRecuperacion VARCHAR(255) NULL AFTER Saldo,
    ADD COLUMN IF NOT EXISTS ExpiracionToken DATETIME NULL AFTER TokenRecuperacion,
    ADD COLUMN IF NOT EXISTS BaneadoHasta DATETIME NULL DEFAULT NULL AFTER ExpiracionToken,
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(50) NOT NULL DEFAULT 'Activo' AFTER BaneadoHasta;

UPDATE Usuarios
SET Saldo = 0.00
WHERE Saldo IS NULL;
