USE carpooling;

ALTER TABLE Vehiculos
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente' AFTER Patente;

CREATE TABLE IF NOT EXISTS Soporte (
    ID_soporte INT AUTO_INCREMENT PRIMARY KEY,
    ID_usuario INT NOT NULL,
    Asunto VARCHAR(150) NOT NULL,
    Mensaje TEXT NOT NULL,
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    Estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    FOREIGN KEY (ID_usuario) REFERENCES Usuarios(ID_usuario) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RetirosAdmin (
    ID_retiro INT AUTO_INCREMENT PRIMARY KEY,
    Monto DECIMAL(10,2) NOT NULL,
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
