USE carpooling;

-- Script de actualizacion para bases existentes.
-- Ejecutar sobre una copia o despues de hacer backup desde phpMyAdmin/panel admin.
-- No borra datos: solo agrega columnas/tablas faltantes y normaliza estados usados por el codigo actual.

ALTER TABLE Usuarios
    ADD COLUMN IF NOT EXISTS DniFrenteImagen MEDIUMTEXT NULL AFTER DNI,
    ADD COLUMN IF NOT EXISTS DniDorsoImagen MEDIUMTEXT NULL AFTER DniFrenteImagen,
    ADD COLUMN IF NOT EXISTS FotoPerfil MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS Descripcion TEXT NULL,
    ADD COLUMN IF NOT EXISTS Preferencias TEXT NULL,
    ADD COLUMN IF NOT EXISTS Saldo DECIMAL(10,2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS TokenRecuperacion VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS ExpiracionToken DATETIME NULL,
    ADD COLUMN IF NOT EXISTS BaneadoHasta DATETIME NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(50) DEFAULT 'Activo';

UPDATE Usuarios SET Saldo = 0.00 WHERE Saldo IS NULL;
UPDATE Usuarios SET Estado = 'Activo' WHERE Estado IS NULL OR Estado = '';

ALTER TABLE Conductores
    ADD COLUMN IF NOT EXISTS FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS BaneadoHasta DATETIME NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS TelefonoContacto VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS AliasMP VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS FotoCarnet MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS FotoCara MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS vehiculo_activo_id INT NULL;

ALTER TABLE Conductores
    MODIFY COLUMN Estado VARCHAR(50) DEFAULT 'Esperando';

UPDATE Conductores
SET Estado = 'Esperando'
WHERE Estado = 'Pendiente';

ALTER TABLE Vehiculos
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente' AFTER Patente,
    ADD COLUMN IF NOT EXISTS FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS Foto MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS PapelesAuto MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS FotoFrente MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS FotoCostado MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS FotoAtras MEDIUMTEXT NULL;

ALTER TABLE Publicaciones
    ADD COLUMN IF NOT EXISTS CalleSalida VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS DistanciaKM INT NULL,
    ADD COLUMN IF NOT EXISTS DuracionMinutos INT NULL;

ALTER TABLE Reservas
    ADD COLUMN IF NOT EXISTS CodigoAcceso VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS TipoPasaje ENUM('propio','tercero') NOT NULL DEFAULT 'propio',
    ADD COLUMN IF NOT EXISTS PasajeroNombre VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS PasajeroApellido VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS PasajeroDNI VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS PasajeroTelefono VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS PasajeroCorreo VARCHAR(150) NULL,
    ADD COLUMN IF NOT EXISTS ID_usuario_responsable INT NULL;

ALTER TABLE Calificaciones
    ADD COLUMN IF NOT EXISTS ID_reserva INT NULL,
    ADD COLUMN IF NOT EXISTS Fecha DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Reportes
    ADD COLUMN IF NOT EXISTS ID_publicacion INT NULL,
    ADD COLUMN IF NOT EXISTS ID_usuario_reportante INT NULL;

ALTER TABLE Notificaciones
    ADD COLUMN IF NOT EXISTS AccionURL VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS AccionLabel VARCHAR(80) NULL,
    ADD COLUMN IF NOT EXISTS AccionSecundariaURL VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS AccionSecundariaLabel VARCHAR(80) NULL;

CREATE TABLE IF NOT EXISTS RetirosAdmin (
    ID_retiro INT AUTO_INCREMENT PRIMARY KEY,
    Monto DECIMAL(10,2) NOT NULL,
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ReportesPasajeros (
    ID_reporte_pasajero INT AUTO_INCREMENT PRIMARY KEY,
    ID_reserva INT NOT NULL,
    ID_usuario_reportado INT NOT NULL,
    ID_usuario_responsable INT NULL,
    ID_conductor INT NOT NULL,
    Motivo VARCHAR(80) NOT NULL,
    Descripcion TEXT NULL,
    Estado VARCHAR(30) NOT NULL DEFAULT 'Pendiente',
    Fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_reserva) REFERENCES Reservas(ID_reserva) ON DELETE CASCADE,
    FOREIGN KEY (ID_usuario_reportado) REFERENCES Usuarios(ID_usuario) ON DELETE CASCADE,
    FOREIGN KEY (ID_usuario_responsable) REFERENCES Usuarios(ID_usuario) ON DELETE SET NULL,
    FOREIGN KEY (ID_conductor) REFERENCES Conductores(ID_conductor) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ConfirmacionesViaje (
    ID_confirmacion INT AUTO_INCREMENT PRIMARY KEY,
    ID_reserva INT NOT NULL UNIQUE,
    ID_usuario INT NOT NULL,
    ID_publicacion INT NOT NULL,
    ConfirmoLlegada BOOLEAN NOT NULL DEFAULT TRUE,
    FechaConfirmacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_reserva) REFERENCES Reservas(ID_reserva) ON DELETE CASCADE,
    FOREIGN KEY (ID_usuario) REFERENCES Usuarios(ID_usuario) ON DELETE CASCADE,
    FOREIGN KEY (ID_publicacion) REFERENCES Publicaciones(ID_publicacion) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ConfirmacionesConductorViaje (
    ID_confirmacion INT AUTO_INCREMENT PRIMARY KEY,
    ID_publicacion INT NOT NULL UNIQUE,
    ID_conductor INT NOT NULL,
    Estado VARCHAR(30) NOT NULL DEFAULT 'Todo bien',
    FechaConfirmacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_publicacion) REFERENCES Publicaciones(ID_publicacion) ON DELETE CASCADE,
    FOREIGN KEY (ID_conductor) REFERENCES Conductores(ID_conductor) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Soporte (
    ID_soporte INT AUTO_INCREMENT PRIMARY KEY,
    ID_usuario INT NOT NULL,
    Asunto VARCHAR(150) NOT NULL,
    Mensaje TEXT NOT NULL,
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    Estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    FOREIGN KEY (ID_usuario) REFERENCES Usuarios(ID_usuario) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BusquedasViajes (
    ID_busqueda INT AUTO_INCREMENT PRIMARY KEY,
    ID_usuario INT NULL,
    CiudadOrigen VARCHAR(100) NULL,
    CiudadDestino VARCHAR(100) NULL,
    Orden VARCHAR(50) NULL,
    Resultados INT NOT NULL DEFAULT 0,
    IP VARCHAR(45) NULL,
    UserAgent VARCHAR(255) NULL,
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_usuario) REFERENCES Usuarios(ID_usuario) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
